# Generated by Django 5.1.4 on 2025-01-06 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='timer_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='todo',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
